spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/feelink
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  date:
    redis:
      host: localhost
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8080