spring:
  config:
    import:
      - optional:file:.env[.properties]  # .properties 추가
  application:
    name: Feelink
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
  messages:
    basename: messages
    encoding: UTF-8
openai:
  api-key: ${OPENAI_API_KEY}
  api-url: ${OPENAI_API_URL}
  model: ${OPENAI_MODEL}