spring:
  application:
    name: Feelink
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
  messages:
    basename: messages
    encoding: UTF-8